---
order: 7  
nav:
  title: 面试知识点
  path: /konwledge
---

## 什么是作用域
### 举个例子
```js
let x=1'
```
一个简单的语句包含了几个基本的概念
- 变量：里x就是一个变量，是用来指代一个值的符号。
- 值：就是具体的数据，可以是数字，字符串，对象等。这里1就是一个值。
- 变量绑定：就是变量和值之间建立对应关系，x = 1就是将变量x和1联系起来了。
- 作用域：作用域就是变量绑定(name binding)的有效范围。就是说在这个作用域中，这个变量绑定是有效的，出了这个作用域变量绑定就无效了。

### 作用域类型
#### 词法作用域（静态）
`词法作用域`是在写代码或者定义时确定的，关注函数在何处声明，作用域链基于代码嵌套。

```js

let x = 10;

function f() {
  return x;
}

function g() {
  let x = 20;
  return f();
}

console.log(g());  // 10


```
也就是说我们调用一个函数时，如果这个函数的变量没有在函数中定义，就去定义该函数的地方查找，这种查找关系在我们代码写出来的时候其实就确定了，所以叫`词法作用域`。

#### 动态作用域
`动态作用域`是在运行时确定的（this也是），关注函数从何处调用，作用域链基于调用栈。

JavaScript并不具备动态作用域，它只有词法作用域。但是`this`机制某种程度上很像`动态作用域`。
```js
function foo() {
    console.log( a ); // 3(不是2！)
}

function bar() {
    var a = 3;
    foo();
}

var a = 2;
bar();
```



### 声明提前

#### 变量声明提前
在ES6之前，我们申明变量都是使用`var`，使用`var`申明的变量都是函数作用域，即在函数体内可见，这会带来的一个问题就是申明提前。

```js
var x = 1;
function f() {
  console.log(x);
  var x = 2;
}

f();
```
上述代码的输出是`undefined`，因为函数f里面的变量`x`使用`var`申明，所以他其实在整个函数`f`可见，也就是说，他的声明相当于提前到了`f`的最顶部，但是赋值还是在运行的`x = 2`时进行，所以在`var x = 2`;上面打印`x`就是`undefined`，上面的代码其实等价于:


```js
var x = 1;
function f() {
  var x
  console.log(x);
  x = 2;
}

f();

```

#### 函数声明提前

```js
function f() {
  x();
  
  function x() {
    console.log(1);
  }
}

f();
```
上述代码`x()`调用是可以成功的，因为函数的声明也会提前到当前函数的最前面，也就是说，上面函数`x`会提前到`f`的最顶部执行

但是有一点需要注意，上面的x函数如果换成函数表达式就不行了:

```js
function f() {
  x();
  
  var x = function() {
    console.log(1);
  }
}

f();

```

这样写会报错`Uncaught TypeError: x is not a function`。因为这里的`x`其实就是一个普通变量，只是它的值是一个函数，它虽然会提前到当前函数的最顶部申明，但是就像前面讲的，这时候他的值是`undefined`，将`undefined`当成函数调用，肯定就是`TypeError`。

#### 变量申明和函数申明提前的优先级

```js
var x = 1;
function x() {}

console.log(typeof x);  // number

```

上述代码我们申明了一个变量`x`和一个函数`x`，他们拥有同样的名字。最终输出来的`typeof`是`number`，说明函数申明的优先级更高，`x`变量先被申明为一个函数，然后当我们再用var申明x的时候，这个var会被忽略，但是`x=1`的赋值语句会运行，最后`x`就是1，类型是`number`。


### 块级作用域（try/catch 、let、const）
ES6引入了`块级作用域`。块级作用域就是指变量在指定的代码块里面才能访问，也就是一对{}中可以访问，在外面无法访问。

#### const、let
ES6引入了`let`关键字，可以将变量绑定到所在的任意作用域中（通常是{ .. }内部），即let为其声明的变量`隐式`地劫持了所在的块作用域。`const` 大体与let相似，但是const 声明的是固定的常量

```js
function f() {
  var x = 2;
  let y = 1;
  const z = 3;
  
  if(true) {
    var  x = 10
    let  y = 2;
    const  z = 4
  }
  
  console.log(x);   // 10
  console.log(y);   // 1
  console.log(z);   // ReferenceError
}
f();
```

因为y z 是let、const声明的，所以他只在他们块级作用域生效。

那用let声明后，在前面引用后会报错，那let就不会变量提升了吗？

```js
var x = 1;
if(true) {
  console.log(x);
  
  let x = 2;
}

```

上述代码会报错`Uncaught ReferenceError: Cannot access 'x' before initialization`。如果let申明的x没有变量提升，那我们在他前面console应该拿到外层var定义的x才对。但是现在却报错了，说明执行器在if这个块里面其实是提前知道了下面有一个let申明的x的，所以说变量完全不提升是不准确的。只是提升后的行为跟var不一样，var是读到一个`undefined`，而块级作用域的提升行为是会制造一个暂时性死区(`temporal dead zone, TDZ`)。暂时性死区的现象就是在块级顶部到变量正式申明这块区域去访问这个变量的话，直接`报错`，这个是ES6规范规定的。

- 循环语句中使用let
下面这种问题我们也经常遇到，在一个循环中调用异步函数，期望是每次调用都拿到对应的循环变量，但是最终拿到的却是最后的循环变量:

```js

for(var i = 0; i < 3; i++) {
  setTimeout(() => {
    console.log(i)
  })
}

```
上述代码我们期望的是输出0,1,2，但是最终输出的却是三个3，这是因为setTimeout是异步代码，会在下次事件循环执行，而i++却是同步代码，而全部执行完，等到setTimeout执行时，i++已经执行完了，此时i已经是3了。以前为了解决这个问题，我们一般采用自执行函数:

```js
for(var i = 0; i < 3; i++) {
  (function(i) {
    setTimeout(() => {
      console.log(i)
    })
  })(i)
}

```
现在有了let我们直接将var改成let就可以了：


```js
for(let i = 0; i < 3; i++) {
  setTimeout(() => {
    console.log(i)
  })
}
```


#### try/catch
ES3规范中规定try/catch的catch分句会创建一个块作用域，其中声明的变量仅在catch中有效。

```js
try {
    undefined(); // 执行一个非法操作来强制制造一个异常
}
catch (err) {
    console.log( err ); // 能够正常执行！
}

console.log( err )； // ReferenceError: err not found

```

当同一个作用域中的两个或多个`catch`分句用同样的标识符名称声明错误变量时，很多静态检查工具还是会发出警告，`实际上这并不是重复定义`，因为所有变量都会安全地限制在块作用域内部。


### 作用域嵌套（作用域链）
遍历嵌套`作用域链`的规则：引擎从当前的`执行作用域`开始查找变量，如果找不到就向`上一级`继续查找。当抵达`最外层`的全局作用域时，无论找到还是没有找到，查找过程都会停止。

```js
let x = 1;

function f() {
  function f1() {
    console.log(x);
  }
  
  f1();
}

f();
```

这段代码在`f1`中输出了`x`，所以他会在`f1`中查找这个变量，当然没找到，然后去`f`中找，还是没找到，再往上去全局作用域找，这下找到了。这个查找链条就是`作用域链`。


## 未完待续......